server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: 'product-service'
  datasource:
    username: 'juke'
    password: 'password'
    url: 'jdbc:postgresql://localhost:5432/product'
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        format_sql: true
    open-in-view: true